/**:
  kvaser_reader:
    ros__parameters:
      hardware_id: 68579
      circuit_id: 0
      bit_rate: 500000
      enable_echo: false
  kvaser_writer:
    ros__parameters:
      hardware_id: 68579
      circuit_id: 0
      bit_rate: 500000
      enable_echo: false
