/**:
  ros__parameters:
    walkway:
      stop_duration: 0.1 # [s] stop time at stop position
      stop_distance_from_crosswalk: 0.0 # [m] make stop line away from crosswalk when no explicit stop line exists
