base_link2livox_front_left_base_link:
  pitch: -0.026
  roll: 0.014
  x: 3.38
  y: 0.672172
  yaw: 0.848
  z: 0.315
base_link2livox_front_right_base_link:
  pitch: -3.113
  roll: 3.16
  x: 3.34
  y: -0.71
  yaw: 2.271
  z: 0.305
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.0465
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.426
  roll: -3.175
  x: -0.35
  y: 0.01
  yaw: -0.042
  z: 1.6
