base_link2livox_front_left_base_link:
  pitch: -0.01
  roll: -0.02
  x: 3.38
  y: 0.58
  yaw: 0.845
  z: 0.32
base_link2livox_front_right_base_link:
  pitch: -3.117
  roll: 3.157
  x: 3.38
  y: -0.65
  yaw: 2.243
  z: 0.33
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.025
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.418
  roll: -3.153
  x: -0.4
  y: 0.02
  yaw: 0.0
  z: 1.6
