base_link2livox_front_left_base_link:
  pitch: 0.0
  roll: -0.01
  x: 3.36
  y: 0.68
  yaw: 0.852876
  z: 0.32
base_link2livox_front_right_base_link:
  pitch: -3.11
  roll: 3.1287
  x: 3.36
  y: -0.68
  yaw: 2.255
  z: 0.35
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.021
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.435
  roll: -3.143
  x: -0.4
  y: 0.02
  yaw: -0.02
  z: 1.67
