base_link2livox_front_left_base_link:
  pitch: -0.01
  roll: -0.015
  x: 3.36
  y: 0.68
  yaw: 0.839
  z: 0.294
base_link2livox_front_right_base_link:
  pitch: -3.115
  roll: 3.149
  x: 3.31
  y: -0.74
  yaw: 2.264
  z: 0.31
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.0245
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.427
  roll: -3.166
  x: -0.35
  y: -0.01
  yaw: -0.04
  z: 1.595
