base_link2sensor_kit_base_link:
  x: 0.6895
  y: 0.0
  z: 2.10
  roll: 0.0
  pitch: -0.02
  yaw: -0.059
base_link2livox_front_right_base_link:
  x: 3.38
  y: -0.65
  z: 0.424839
  roll: 3.1287
  pitch: -3.13127
  yaw: 2.25
base_link2livox_front_left_base_link:
  x: 3.38
  y: 0.672172
  z: 0.409508
  roll: 0.01
  pitch: -0.00851071
  yaw: 0.852876
base_link2velodyne_rear_base_link:
  x: -0.40
  y: 0.02
  z: 1.67
  roll: -3.143
  pitch: 2.435
  yaw: 0.00