sensor_kit_base_link2camera0:
  x: 0.215
  y: 0.031
  z: -0.024
  roll: -0.010
  pitch: 0.002
  yaw: 0.041
sensor_kit_base_link2camera1:
  x: -0.111
  y: -0.020
  z: -0.084
  roll: -0.010
  pitch: -0.016
  yaw: -3.106
sensor_kit_base_link2camera2:
  x: 0.087
  y: 0.581
  z: -0.274
  roll: -0.008
  pitch: 0.354
  yaw: 1.101
sensor_kit_base_link2camera3:
  x: -0.122
  y: 0.570
  z: -0.254
  roll: 0.010
  pitch: 0.353
  yaw: 2.152
sensor_kit_base_link2camera4:
  x: 0.083
  y: -0.580
  z: -0.234
  roll: 0.003
  pitch: 0.359
  yaw: -0.981
sensor_kit_base_link2camera5:
  x: -0.078
  y: -0.565
  z: -0.254
  roll: -0.021
  pitch: 0.369
  yaw: -2.036 
sensor_kit_base_link2traffic_light_right_camera:
  x: 0.520
  y: 0.052
  z: -0.144
  roll: 0.00
  pitch: 0.027
  yaw: 0.045
sensor_kit_base_link2traffic_light_left_camera:
  x: 0.431
  y: -0.148
  z: -0.135
  roll: 0.00
  pitch: 0.038
  yaw: 0.043
sensor_kit_base_link2velodyne_top_base_link:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 0.0
  pitch: 0.0
  yaw: 1.575
sensor_kit_base_link2velodyne_left_base_link:
  x: -0.017
  y: 0.598
  z: -0.301
  roll: -0.023
  pitch: 0.71
  yaw: 1.591
sensor_kit_base_link2velodyne_right_base_link:
  x: -0.027
  y: -0.552
  z: -0.294
  roll: -0.016
  pitch: 0.708
  yaw: -1.543
sensor_kit_base_link2gnss:
  x: -0.1
  y: 0.0
  z: -0.2
  roll: 0.0
  pitch: 0.0
  yaw: 0.0
sensor_kit_base_link2imu_tamagawa:
  x: 0.0
  y: 0.0
  z: 0.0
  roll: 3.14159265359
  pitch: 0.0
  yaw: 3.14159265359