base_link2livox_front_left_base_link:
  pitch: -0.006
  roll: -0.0245
  x: 3.35
  y: 0.715
  yaw: 0.852
  z: 0.315
base_link2livox_front_right_base_link:
  pitch: -3.117
  roll: 3.148
  x: 3.32
  y: -0.71
  yaw: 2.262
  z: 0.31
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.0405
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.42
  roll: -3.16
  x: -0.35
  y: 0.01
  yaw: -0.028
  z: 1.6
