base_link2livox_front_left_base_link:
  pitch: -0.007
  roll: -0.026
  x: 3.38
  y: 0.67
  yaw: 0.803
  z: 0.31
base_link2livox_front_right_base_link:
  pitch: -3.107
  roll: 3.146
  x: 3.34
  y: -0.72
  yaw: 2.264
  z: 0.335
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.04
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.425
  roll: -3.14
  x: -0.34
  y: 0.0
  yaw: -0.013
  z: 1.58
