/**:
  ros__parameters:
    filter_target_label:
      UNKNOWN : true
      CAR : false
      TRUCK : false
      BUS : false
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false
    # object footprint ratio threshold to be considered as inside lanelet
    # should be greater than 0.0
    inside_lanelet_footprint_ratio_threshold: 0.4
