base_link2livox_front_left_base_link:
  pitch: -0.028
  roll: -0.019
  x: 3.36
  y: 0.68
  yaw: 0.858
  z: 0.34
base_link2livox_front_right_base_link:
  pitch: -3.119
  roll: 3.16
  x: 3.32
  y: -0.71
  yaw: 2.261
  z: 0.33
base_link2sensor_kit_base_link:
  pitch: -0.02
  roll: 0.0
  x: 0.6895
  y: 0.0
  yaw: -0.041
  z: 2.1
base_link2velodyne_rear_base_link:
  pitch: 2.417
  roll: -3.169
  x: -0.35
  y: -0.01
  yaw: -0.037
  z: 1.585
